name: Test CI

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.0.0

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Compile DSDL sources
        run: uv run cyphal install

      - name: Cache pre-commit environment
        uses: actions/cache@v5
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Lint and static checks
        run: uv run make check

      - name: Verify check made no changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "make check modified files. Please run make check locally and commit the updates."
            git --no-pager diff
            exit 1
          fi

      - name: Run tests
        run: uv run make test
